version: '3.8'

services:

  #Application
  user_service:
    container_name: user_service
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - postgresql_user_service
    restart: unless-stopped

  #PostgreSQL
  postgresql_user_service:
    container_name: postgresql_user_service
    image: postgres:latest
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
    ports:
      - "6001:5432"
    volumes:
      - db_user_service:/var/lib/postgresql/data
    restart: unless-stopped

#Volumes
volumes:
  db_user_service:
    driver: local
